source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FTMoreApps_Example', :exclusive => true do
  pod "FTMoreApps", :path => "../"
end

target 'FTMoreApps_Tests', :exclusive => true do
  pod "FTMoreApps", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
